.PHONY: build up start stop down status exec

build:
	docker-compose build

up:
	docker-compose up -d

start:
	docker-compose start

stop:
	docker-compose stop

down:
	docker-compose down

status:
	docker-compose ps

exec:
	docker-compose exec apache /bin/sh